name: Handle pull request

on:
  push:
  pull_request:
    branches:
      - develop
      - master
  workflow_dispatch:

jobs:

  call-build-test:
    needs: show-variables
    uses: ./.github/workflows/build-test.yml
    with: 
      release-version: '0.0.0'


