name: Handle release

on:
  push:
    tags: 
      - '[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

      #- 'releases/[1-9]+.[0-9]+.[0-9]+'
jobs:
  check-tag-branch:
    # This job is based on replies in https://github.community/t/how-to-create-filter-on-both-tag-and-branch/16936/6
    runs-on: ubuntu-latest
    steps:
    - name: Get tag commit hash
      id: tag-commit-hash
      run: |
        hash=${{ github.sha }}
        echo "::set-output name=tag-hash::${hash}"
        echo $hash

    - name: checkout master
      uses: actions/checkout@v3
      with:
        ref: master

    - name: Get latest master commit hash
      id: master-commit-hash
      run: |
        hash=$(git log -n1 --format=format:"%H")
        echo "::set-output name=master-hash::${hash}"
        echo $hash

    - name: Exit if tag commit hash don't match master commit hash
      if: steps.tag-commit-hash.outputs.tag-hash != steps.master-commit-hash.outputs.master-hash
      run: |
        echo "Tag was not on the master branch. Exiting."
        exit 1

  get-version:
    runs-on: windows-2022 #ubuntu-latest
    needs: check-tag-branch
    steps:
    - name: Get version from tag
      id: extract-tag
      shell: bash
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    
    - name: Check output to get version number
      run: |
        echo "release_version is $env:RELEASE_VERSION"
        if ($env:RELEASE_VERSION -eq $null -or $env:RELEASE_VERSION -eq '') {
          echo "Setting release version to 0.0.0"
          echo "RELEASE_VERSION=0.0.0" >> $env:GITHUB_ENV
        }

    - name: Dump env
      run: env | sort 

    outputs:
        release-version: ${{ env.RELEASE_VERSION }}

  show-variables:
    needs: get-version
    runs-on: windows-2022
    steps:

    - name: Dump env
      run: env | sort
   
    - name: Dump GitHub context
      env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Show release version input
      run: echo "needs.get-version.outputs.release-version  ${{ needs.get-version.outputs.release-version }} - so"

  call-build-test:
    needs: get-version
    uses: ./.github/workflows/build-test.yml
    with: 
      release-version: ${{ needs.get-version.outputs.release-version }}

  publish-it:
    needs: [get-version, call-build-test]
    uses: ./.github/workflows/publish.yml
    with: 
      release-version: ${{ needs.get-version.outputs.release-version }}