name: publish
  
on: 
  workflow_call:
  workflow_dispatch:


env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release
  PLATFORM: Any CPU

jobs:
  publish:
    name: publish
    runs-on: windows-2022

    steps:

    - name: Dump env
      run: env | sort
   
    - name: Dump GitHub context
      env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
      
    - uses: actions/checkout@v3

    #- name: See what we got
    #  run: dir  $env:GITHUB_WORKSPACE\SimpleWinForms\bin\Release

    - name: Get cached build
      id: get-cached-build
      uses: actions/cache@v3.0.5
      with:
        path: src/SimpleWinForms/bin/Release
        key: cached-output

    - name: Did we get the cache
      if: steps.get-cached-build.outputs.cache-hit == 'true'
      run: echo "We got the DUKE!"

    - name: Did we get the cache
      if: steps.get-cached-build.outputs.cache-hit != 'true'
      run: echo "We dont have the duke"

    #- name: See what we got
    #  run: dir  $env:GITHUB_WORKSPACE\SimpleWinForms\bin\Release

    - name: show build number works
      run: echo "GITHUB_RUN_ID is $env:GITHUB_RUN_ID"
      
    - name: show build number 2 - not works
      run: echo "GITHUB_RUN_ID is ${{env.GITHUB_RUN_ID}}"

    - name: show build just 
      run: echo "BUILD_CONFIGURATION is $BUILD_CONFIGURATION"

    - name: show build -wroks
      run: echo "BUILD_CONFIGURATION is ${{env.BUILD_CONFIGURATION}}"
      
    - name: Show workspace
      run: echo "GITHUB_WORKSPACE using env $env:GITHUB_WORKSPACE"

    - name: Create filenames for zip and nupkg
      run: |
        $stepFilename = "simpleWinForms-$($env:RELEASE_VERSION)"
        echo "ZipFilename=$stepFilename.zip" >> $env:GITHUB_ENV

    - name: Dump env
      run: env | sort
   
    - name: Compress output
      run: |
        7z a $env:ZipFilename $env:GITHUB_WORKSPACE\src\SimpleWinForms\bin\Release\*.*
        
    - name: Create the release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
      continue-on-error: true
      run: |
        gh release create ${{ env.RELEASE_VERSION }}  --draft --generate-notes

    - name: Upload build output zipped
    # missing $env:NupkgFilename on the gh command line
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        gh release upload ${{ env.VERSION }}  $env:ZipFilename 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
