name: SHow secret

on:
  push:
  workflow_dispatch:

      #- 'releases/[1-9]+.[0-9]+.[0-9]+'
jobs:
  show-variables:
    runs-on: windows-2022
    steps:

    - name: Dump env
      run: env | sort
   
    - name: Dump GitHub context
      env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Show secret
      run: echo ${CHOKOTOKEN:0:4}; 

    - name: Show secret directly
      run: |
        echo "Begins with $("${{ secrets.CHOKOTOKEN }}".substring(0,3))"

    - name: Show secret through env
      env: 
        CHOCO_TOKEN: ${{ secrets.CHOKOTOKEN }}
      run: |
        echo "Begins with $($env:CHOCOTOKEN.substring(0,3))"
